CC     = gcc
CFLAGS = -Wall -Wextra -std=c11

BIN    = menu-heap-or-quick

SRC    = menu.c heap.c
OBJ    = $(SRC:.c=.o)

$(BIN): $(OBJ)
	$(CC) $(OBJ) -o $(BIN)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: run valgrind clean

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(OBJ) $(BIN)
